# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"

    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"

    - PYTHON: "C:\\Python35"
      TOXENV: "py35"

    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37"
      TOXENV: "py37"

    - PYTHON: "C:\\Python37-x64"
      TOXENV: "py37"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "py -V"
  - "py -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "py -m pip install --upgrade pip"
  - "py -m pip install tox wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "py -m tox"

after_test:
  - "py setup.py bdist_wheel"
  - ps: "ls dist"

on_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - "py -m pip install codecov"
    - set OS=WINDOWS
    - "py -e TOXENV OS"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
